log_level: DEBUG
search_concurrency: 1
search_rate: 1
token_ttl: 1m
words_address: localhost:28081
update_address: localhost:28082
search_address: localhost:28083
yolo_address: localhost:28085
api_server:
  address: localhost:28080
  timeout: 5s
