FROM golang:1.23 AS build

RUN apt update
ENV PATH="$PATH:$(go env GOPATH)/bin"

COPY go.mod go.sum /src/
COPY comic-frontend  /src/comic-frontend

RUN cd /src

ENV CGO_ENABLED=0
RUN cd /src && go build -o /comic-frontend  comic-frontend/main.go

FROM alpine:3.20

COPY --from=build /comic-frontend  /comic-frontend

ENTRYPOINT [ "/comic-frontend" ]